preBuildCommand: cd backend && npm install
buildCommand: npm run build
startCommand: cd backend && npm start
env:
  MONGODB_URI:
    syn: false
  JWT_SECRET: agrishield_ai_secret_2026
  WEATHER_API_KEY: 09043d37fbaf47dc1c785458c7385a7c
  PORT: 10000
